#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#             MicroCommands by FlailoftheLord.                     #
#         -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                  #
#   for questions please pm me on discord at FlailoftheLord#6842   #
#          Join my discord server for faster support:              #
#                https://discord.gg/wuxW5PS                        #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# Welcome to my awesome little plugin, its probably really lame,
# because theres lots of other 'Essentials' type plugins out there
# But i promise i shall make your experience with this plugin truly unique!!
# thanks for trying it out and i hope you enjoy!
#   If you have any suggestions for improvement, or any feedback...
#  just pm me on Discord (linked above) or join my discord server! (linked above)
