main: me.flail.MicroCommands.MicroCommands
name: MicroCommands
version: 1.0.0
api-version: 1.13
author: FlailoftheLord
description: Every essential command your server will ever need :>
soft-depend: [Vault, PlaceholderAPI, ProtocolLib]

Commands:
  
  microcommands:
    description: main command for the plugin
    usage: /microcommands [help:reload]
    aliases: [mcc, microcmd, mmcc, mmicrocmd, mmicrocommands]
    
  me:
    description: replaces the default minecraft /me
    usage: /action <message>
    aliases: [action, maction, mme]
    
  fly:
    description: fly command
    usage: /fly [player] [on/off]
    aliases: [mfly]
    
  teleport:
    description: teleport command
    usage: /teleport <location:player> [location:player]
    aliases: [tp, tpo, tpa, tpaccept, tpdeny, tpacancel, tptoggle, toggletp, mtp, mtpo, mtpa, mtpdeny, mtpaccept, mtpacancel, mtoggletp, mtptoggle]
    
  
  mnms:
    description: lel
    usage: /mnms
  
Permissions:
  
  microcommands.command:
    description: use the main /microcommands command
    default: op
    
  microcommands.op:
    description: every single permission, acts as a wildcard permission for MicroCommands
    default: false
    children:
      microcommands.command: true
      microcommands.fly: true
      microcommands.bypass.all: true
      microcommands.exempt.all: true
      
      
      
      
      