#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#             MicroCommands by FlailoftheLord.                     #
#         -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                  #
#           If you have any Questions or feedback                  #
#              Join my discord server here:                        #
#               https://discord.gg/wuxW5PS                         #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# Welcome to my awesome little plugin, its probably really lame,
# because theres lots of other 'Essentials' type plugins out there
# But i promise i shall make your experience with this plugin truly unique!!
# thanks for trying it out and i hope you enjoy!
#   If you have any suggestions for improvement, or any feedback...
#  just join my discord server! (linked above) or pm me on SpigotMC.


# Custom join and leave messages
# for multiple lines simply format it like this ->
#  JoinMessage: |-
#    &cfirst line hello....!
#    &asecon line...
#    &ethird line! woot woot!
# set to false to disable join and leave messages
JoinLeaveMessages: true
JoinMessage: "$prefix$ &e$player$ &7returned!"
LeaveMessage: "$prefix$ &e$player$ &cleft the game."
FirstJoinMessage: "$prefix$ &a$player$ &3has joined for the first time, welcome him!"

ChatFormat: "&f$player$ &8» &7&l$message$"

# Command override list
# These commands will always override other plugins
# for example if another plugin uses the command /fly, add it to this list to force the server to use MicroCommands.
ForcedCommands:
- msg

# List all commands here that you don't want MicroCommands to be able to handle.
DisabledCommands:
- spawn










